# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui_outils_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_OutilsDialog(object):
    def setupUi(self, OutilsDialog):
        OutilsDialog.setObjectName("OutilsDialog")
        self.vboxlayout = QtWidgets.QVBoxLayout(OutilsDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupPurpose = QtWidgets.QGroupBox(OutilsDialog)
        self.groupPurpose.setObjectName("groupPurpose")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.groupPurpose)
        self.hboxlayout.setObjectName("hboxlayout")
        self.comboPurpose = QtWidgets.QComboBox(self.groupPurpose)
        self.comboPurpose.setObjectName("comboPurpose")
        self.comboPurpose.addItem("")
        self.comboPurpose.addItem("")
        self.comboPurpose.addItem("")
        self.comboPurpose.addItem("")
        self.comboPurpose.addItem("")
        self.comboPurpose.addItem("")
        self.hboxlayout.addWidget(self.comboPurpose)
        self.btnFilterPurpose = QtWidgets.QPushButton(self.groupPurpose)
        self.btnFilterPurpose.setObjectName("btnFilterPurpose")
        self.hboxlayout.addWidget(self.btnFilterPurpose)
        self.btnClearFilters = QtWidgets.QPushButton(self.groupPurpose)
        self.btnClearFilters.setObjectName("btnClearFilters")
        self.hboxlayout.addWidget(self.btnClearFilters)
        self.vboxlayout.addWidget(self.groupPurpose)
        self.groupScale = QtWidgets.QGroupBox(OutilsDialog)
        self.groupScale.setObjectName("groupScale")
        self.gridlayout = QtWidgets.QGridLayout(self.groupScale)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtWidgets.QLabel(self.groupScale)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.editScale = QtWidgets.QLineEdit(self.groupScale)
        self.editScale.setObjectName("editScale")
        self.gridlayout.addWidget(self.editScale, 0, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(self.groupScale)
        self.label1.setObjectName("label1")
        self.gridlayout.addWidget(self.label1, 1, 0, 1, 1)
        self.editMaxScale = QtWidgets.QLineEdit(self.groupScale)
        self.editMaxScale.setObjectName("editMaxScale")
        self.gridlayout.addWidget(self.editMaxScale, 1, 1, 1, 1)
        self.btnApplyScale = QtWidgets.QPushButton(self.groupScale)
        self.btnApplyScale.setObjectName("btnApplyScale")
        self.gridlayout.addWidget(self.btnApplyScale, 2, 0, 1, 2)
        self.vboxlayout.addWidget(self.groupScale)
        self.buttonBox = QtWidgets.QDialogButtonBox(OutilsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(OutilsDialog)
        QtCore.QMetaObject.connectSlotsByName(OutilsDialog)

    def retranslateUi(self, OutilsDialog):
        _translate = QtCore.QCoreApplication.translate
        OutilsDialog.setWindowTitle(_translate("Ui_OutilsDialog", "Outils ENC"))
        self.groupPurpose.setTitle(_translate("Ui_OutilsDialog", "Filtrer les couches par \"purpose\""))
        self.comboPurpose.setItemText(0, _translate("Ui_OutilsDialog", "1 - Vue d’ensemble"))
        self.comboPurpose.setItemText(1, _translate("Ui_OutilsDialog", "2 - Généralités"))
        self.comboPurpose.setItemText(2, _translate("Ui_OutilsDialog", "3 - Côtière"))
        self.comboPurpose.setItemText(3, _translate("Ui_OutilsDialog", "4 - Approche"))
        self.comboPurpose.setItemText(4, _translate("Ui_OutilsDialog", "5 - Port"))
        self.comboPurpose.setItemText(5, _translate("Ui_OutilsDialog", "6 - Accostage"))
        self.btnFilterPurpose.setText(_translate("Ui_OutilsDialog", "Exécuter"))
        self.btnClearFilters.setText(_translate("Ui_OutilsDialog", "Enlever tous les filtres"))
        self.groupScale.setTitle(_translate("Ui_OutilsDialog", "Définir échelles d\'affichage pour les couches sélectionnées"))
        self.label.setText(_translate("Ui_OutilsDialog", "Échelle minimale :"))
        self.editScale.setPlaceholderText(_translate("Ui_OutilsDialog", "ex : 250000"))
        self.label1.setText(_translate("Ui_OutilsDialog", "Échelle maximale :"))
        self.editMaxScale.setPlaceholderText(_translate("Ui_OutilsDialog", "ex : 10000"))
        self.btnApplyScale.setText(_translate("Ui_OutilsDialog", "Appliquer"))
